### ISSUE TITLE
What is this code licensed under?

### ISSUE THREAD

**Issue by tylercrompton** [keybase/saltpack-python#3]
Just trying to figure out if I can legally use it in a project of mine.

**Comment by cgoldberg** [comment]
It is **MIT licensed** according to the installer:
https://github.com/keybase/saltpack-python/blob/0.2.1/setup.py#L14

However, it is missing a copyright notice and a copy of the license (which are both conditions of the MIT license).  To properly license this, a file named `LICENSE` should be added to the root of this repo (a note in the README would be a good idea also).  The `LICENSE` file should contain the text of the license and the copyright attribution.  An example is shown here:  https://opensource.org/licenses/MIT
