### ISSUE TITLE
Only py3 supported?

### ISSUE THREAD

**Issue by mirceaulinic** [keybase/saltpack-python#5]

**Comment by cgoldberg** [comment]
@mirceaulinic,

It appears to be **Python3 only**.

from `setup.py`:
```
if sys.version_info.major < 3:
    print("ERROR: saltpack-python requires Python 3")
    sys.exit(1)
```
----

Notes:

1. a backport probably wouldn't be too difficult
2. I don't recommend maintaining Py2 compatibility at this point
3. if you need it, you can always maintain your own fork
4. I am not a maintainer of this project

**Comment by oconnor663** [comment]
I'm curious about your use case. Are you importing `saltpack` as a library? I mostly intended for people to run this as a CLI command, so I figured Python 2 support wasn't really necessary.

I hope that `3to2` would take care of most of the conversion, but it looks like there's some new syntax that it doesn't know how to convert, like [fancy uses of the `*` character](https://github.com/keybase/saltpack-python/blob/0.2.1/saltpack/encrypt.py#L162).

**Comment by ghost** [comment]
Python 2 has been EOLed for a while now.
